export const mockBooks: BookProperties[] = [
    {
        id: 1,
        bookCover: 'https://example.com/book1.jpg',
        title: "L'Étranger",
        authors: ['Albert Camus'],
        subjects: ['Philosophical Fiction'],
        bookshelves: ['Existentialism'],
        languages: ['French'],
    },
    {
        id: 2,
        bookCover: 'https://example.com/book2.jpg',
        title: 'To Kill a Mockingbird',
        authors: ['Harper Lee'],
        subjects: ['Coming-of-Age'],
        bookshelves: ['Classic'],
        languages: ['English'],
    },
    {
        id: 3,
        bookCover: 'https://example.com/book3.jpg',
        title: 'One Hundred Years of Solitude',
        authors: ['Gabriel García Márquez'],
        subjects: ['Magical Realism'],
        bookshelves: ['Latin American Literature'],
        languages: ['Spanish'],
    },
    {
        id: 11,
        bookCover: 'https://example.com/book11.jpg',
        title: 'The Night Circus',
        authors: ['Erin Morgenstern'],
        subjects: ['Fantasy'],
        bookshelves: ['Magical Realism'],
        languages: ['English'],
    },
    {
        id: 12,
        bookCover: 'https://example.com/book12.jpg',
        title: 'Kafka on the Shore',
        authors: ['Haruki Murakami'],
        subjects: ['Surrealism'],
        bookshelves: ['Japanese Literature'],
        languages: ['Japanese'],
    },
    {
        id: 13,
        bookCover: 'https://example.com/book13.jpg',
        title: 'The Great Gatsby',
        authors: ['F. Scott Fitzgerald'],
        subjects: ['Classic'],
        bookshelves: ['Roaring Twenties'],
        languages: ['English'],
    },
    {
        id: 14,
        bookCover: 'https://example.com/book14.jpg',
        title: 'Crime and Punishment',
        authors: ['Fyodor Dostoevsky'],
        subjects: ['Psychological Fiction'],
        bookshelves: ['Russian Literature'],
        languages: ['Russian'],
    },
    {
        id: 15,
        bookCover: 'https://example.com/book15.jpg',
        title: "The Hitchhiker's Guide to the Galaxy",
        authors: ['Douglas Adams'],
        subjects: ['Science Fiction'],
        bookshelves: ['Humor'],
        languages: ['English'],
    },
    {
        id: 16,
        bookCover: 'https://example.com/book16.jpg',
        title: 'Pride and Prejudice',
        authors: ['Jane Austen'],
        subjects: ['Romance'],
        bookshelves: ['Classic'],
        languages: ['English'],
    },
    {
        id: 17,
        bookCover: 'https://example.com/book17.jpg',
        title: 'Norwegian Wood',
        authors: ['Haruki Murakami'],
        subjects: ['Coming-of-Age'],
        bookshelves: ['Japanese Literature'],
        languages: ['Japanese'],
    },
]
