export const mockBooks: BookProperties[] = [
    {
        _id: '65d7647608b73ff1a8d69395',
        covers: 'https://upittpress.org/wp-content/themes/pittspress/images/no_cover_available.png',
        title: "L'Étranger",
        authors: ['Albert Camus'],
        subjects: ['Philosophical Fiction'],
        languages: ['French'],
        download_count: 10,
    },
    {
        _id: '65d7647608b73ff1a8d69395',
        covers: 'https://www.gutenberg.org/cache/epub/1342/pg1342.cover.medium.jpg',
        title: 'To Kill a Mockingbird',
        authors: ['Harper Lee'],
        subjects: ['Coming-of-Age'],
        languages: ['English'],
        download_count: 20,
    },
    {
        _id: '65d7647608b73ff1a8d69395',
        covers: 'https://www.gutenberg.org/cache/epub/145/pg145.cover.medium.jpg',
        title: 'One Hundred Years of Solitude',
        authors: ['Gabriel García Márquez'],
        subjects: ['Magical Realism'],
        languages: ['Spanish'],
        download_count: 30,
    },
    {
        _id: '65d7647608b73ff1a8d69395',
        covers: 'https://example.com/book11.jpg',
        title: 'The Night Circus',
        authors: ['Erin Morgenstern'],
        subjects: ['Fantasy'],
        languages: ['English'],
        download_count: 1,
    },
    {
        _id: '65d7647608b73ff1a8d69395',
        covers: 'https://example.com/book12.jpg',
        title: 'Kafka on the Shore',
        authors: ['Haruki Murakami'],
        subjects: ['Surrealism'],
        languages: ['Japanese'],
        download_count: 1,
    },
    {
        _id: '65d7647608b73ff1a8d69395',
        covers: 'https://example.com/book13.jpg',
        title: 'The Great Gatsby',
        authors: ['F. Scott Fitzgerald'],
        subjects: ['Classic'],
        languages: ['English'],
        download_count: 2,
    },
    {
        _id: '65d7647608b73ff1a8d69395',
        covers: 'https://example.com/book14.jpg',
        title: 'Crime and Punishment',
        authors: ['Fyodor Dostoevsky'],
        subjects: ['Psychological Fiction'],
        languages: ['Russian'],
        download_count: 3,
    },
    {
        _id: '65d7647608b73ff1a8d69395',
        covers: 'https://example.com/book15.jpg',
        title: "The Hitchhiker's Guide to the Galaxy",
        authors: ['Douglas Adams'],
        subjects: ['Science Fiction'],
        languages: ['English'],
        download_count: 2,
    },
    {
        _id: '65d7647608b73ff1a8d69395',
        covers: 'https://example.com/book16.jpg',
        title: 'Pride and Prejudice',
        authors: ['Jane Austen'],
        subjects: ['Romance'],
        languages: ['English'],
        download_count: 3,
    },
    {
        _id: '65d7647608b73ff1a8d69395',
        covers: 'https://example.com/book17.jpg',
        title: 'Norwegian Wood',
        authors: ['Haruki Murakami'],
        subjects: ['Coming-of-Age'],
        languages: ['Japanese'],
        download_count: 6,
    },
]
